### ISSUE TITLE
I am trying to building this project but getting some error while building it.

### ISSUE THREAD

**Issue by mukesh14149** [blurpy/kouchat-android#13]
I imported this project in my android studio 2.1 and added missing library annotations-12.0.jar
but while i make the module i am getting error in style.xml file
No resource found Theme.Sherlock.Light
... Widget.Sherlock.Light.ActionBar.Solid
... Widget
in parent tag of style.

**Comment by blurpy** [comment]
Have you added ActionBarSherlock? http://actionbarsherlock.com/
See the pom files for a list of dependencies. I have not had the time yet to migrate to gradle.

**Comment by mukesh14149** [comment]
@blurpy  I am interested in this kind of project. I would like to develop such a project for myself. 
I would like to use your project as a reference. But it has no documentation , so much difficult to understand
If you can help me in understanding this project code base or point me to some other good resources that can help me in my project will be great.

**Comment by blurpy** [comment]
That sounds cool!

There is lots of documentation on the functionality on the home page, and lots of javadoc in the code. But there is no architectural documentation anywhere.

I can link you to some of the most important classes in the app.

This is the entry point in the app, the main chat:
https://github.com/blurpy/kouchat-android/blob/master/kouchat-android-impl/src/main/java/net/usikkert/kouchat/android/controller/MainChatController.java

This is the background service that keeps the state in the app:
https://github.com/blurpy/kouchat-android/blob/master/kouchat-android-impl/src/main/java/net/usikkert/kouchat/android/service/ChatService.java

This is the mediator that connects the user interface to the generic kouchat api that is used on both desktop, console and Android:
https://github.com/blurpy/kouchat-android/blob/master/kouchat-android-impl/src/main/java/net/usikkert/kouchat/android/chatwindow/AndroidUserInterface.java

This is the main api provided in the app:
https://github.com/blurpy/kouchat-android/blob/master/kouchat-android-impl/src/main/java/net/usikkert/kouchat/misc/Controller.java

This is responsible for keeping the network connection going:
https://github.com/blurpy/kouchat-android/blob/master/kouchat-android-impl/src/main/java/net/usikkert/kouchat/net/ConnectionWorker.java

These send and receive message over the network:
https://github.com/blurpy/kouchat-android/blob/master/kouchat-android-impl/src/main/java/net/usikkert/kouchat/net/MessageReceiver.java
https://github.com/blurpy/kouchat-android/blob/master/kouchat-android-impl/src/main/java/net/usikkert/kouchat/net/MessageSender.java

Hope this helps.
