### ISSUE TITLE
Switch to Gradle for building

### ISSUE THREAD

**Issue by blurpy** [blurpy/kouchat-android#8]

**Comment by ambrice** [comment]
Currently does not build with newer versions of maven such as the one that comes with Ubuntu 15.10.  Needs newer android-maven-plugin but then that breaks the test build..

**Comment by blurpy** [comment]
Try downloading a zip of an older version of maven in the meantime and use that for building. Hoping to have some time to migrate to gradle soon.

**Comment by blurpy** [comment]
Completed.
